### ISSUE TITLE
Several issues regarding compilation, redirect_uri and mimetype

### ISSUE THREAD

**Issue by FMudanyali** [aitoiaita/linux-jagex-launcher#3]
OS: Arch Linux 32
Compiler: Rust 1.80 stable
Machine: Thinkpad z60m

Hi, I came across several issues trying to run this application and managed to fix them.

The first one is compilation error due to the package time v0.3.29, I removed this package from Cargo.lock, which caused cargo to pull the latest version 0.3.36 which compiled successfully.

The second issue is related to #2 caused by missing redirect_uri parameter in the auth URL. Even with the latest commit, this parameter is absent from the URL, so I appended `&redirect_uri=https://secure.runescape.com/m=weblogin/launcher-redirect` to the URL and it worked. However, when the authorization was done, it did not redirect to the application because there were no programs registered to open the URL `jagex:code=XXXX,state=XXXX`. 

In order to fix this, I created the file `~/.local/share/applications/osrs-launcher.desktop` with following contents:

```
[Desktop Entry]
Version=1.0
Name=OSRS Launcher
Exec=/home/USERNAME/.local/bin/osrs-launcher %u
Terminal=true
Type=Application
MimeType=x-scheme-handler/jagex
```

And then I updated the MIME database with following command:
```
update-desktop-database ~/.local/share/applications
```

Finally, I set the newly created .desktop file as the default for `x-scheme-handler/jagex` type with following command:
```
xdg-mime default osrs-launcher.desktop x-scheme-handler/jagex
```

Now, when I open the program from osrs-launcher.desktop and append redirect_uri parameter to the URL, the authorization works as expected and I am able to play with my desired character.

**Comment by pulsemod** [comment]
I was able to get this working on FreeBSD 14.1 after creating the desktop file and registering the MIME type as shown above.

Since binding to ports < 1024 is naturally not permitted for an unprivileged process on most UNIX systems, I built with a much higher default port number. The page opened to choose a character still points to port 80 regardless in the current code.

Seems like there's nothing Linux specific about this software otherwise? :smile:
Thanks for writing something allowing people who can't use the Jagex Launcher to play.

**Comment by nezzled** [comment]
Hi, having similar issues and it seems the parameter fix doesn't work anymore, at least for me. I get a "something went wrong" screen on the Jagex website with the error denoted in the URL as "common/error?error=invalid_request&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed.+The+'redirect_uri'+parameter+does+not+match+any+of+the+OAuth+2.0+Client's+pre-registered+redirect+urls."
Is there something I'm missing?

**Comment by aitoiaita** [comment]
For the original issue (old):

1. Cargo.lock has been updated, thanks for bringing this up.
2. redirect_uri should have been present in the authorization link this whole time.  The relevant line of code is [here](https://github.com/aitoiaita/linux-jagex-launcher/blob/2e9a9a951bf61f1879c97623cc413b32e1882e9b/src/daemon/consent_client.rs#L115).  If it really isn't being added to the full URL string, I suspect an issue in my fork of oauth-rs.
3. I'll consider adding a section to the README about installing the launcher as the default application to handle jagex: links.  I don't know why this slipped my mind originally.

For @nezzled:
Is this occuring when osrs-launcher opens the consent link - that being, the link beginning with https://account.jagex.com/oauth2/auth?  If it is, make sure that the redirect_uri parameter is specified in the /oauth2/auth URL.  If it isn't, these two issues are probably related somehow.

I haven't been able to replicate the missing redirect_uri param in the time since this issue has been open - like it says above, the code to add the redirect_uri parameter to the URL is there and it works on my machines.  Are you, by chance, running a 32 bit operating system like the OP of this issue is?

**Comment by nezzled** [comment]
@aitoiaita 

> Is this occuring when osrs-launcher opens the consent link - that being, the link beginning with https://account.jagex.com/oauth2/auth? If it is, make sure that the redirect_uri parameter is specified in the /oauth2/auth URL. If it isn't, these two issues are probably related somehow.

I just figured out that the redirect_uri parameter was present in the URL generated by the launcher, which is why the error was occurring... can't believe I missed that. Still, I get stuck on the "almost complete" page and it doesn't seem that the redirect actually does anything. I've set up the mime handling as addressed in this issue and the launcher still does not respond at all.

>  Are you, by chance, running a 32 bit operating system like the OP of this issue is?

Nope, 64-bit.

**Comment by aitoiaita** [comment]
@nezzled 
Try copying the "jagex:..." URL which is given to you through the (if i recall correctly) "Return to launcher" button, and pass it as a parameter to osrs-launcher like so:
`osrs-launcher "jagex:code=...,state=...,intent=social_auth"`
If that works, then your mime-type handling isn't setup correctly.

**Comment by nezzled** [comment]
@aitoiaita 
While replying to this, I retried the steps and you were right. However, it just gets caught on the "launching" step and then stops running. I've confirmed runelite runs via the `runelite` command and functions. No errors are logged.
![Image](https://github.com/user-attachments/assets/cf960208-5cef-49eb-b074-928699e57908)

**Comment by aitoiaita** [comment]
@nezzled 
I'm going to close this issue and move discussion to a new one :)
https://github.com/aitoiaita/linux-jagex-launcher/issues/8
